name: Metrics

on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: tatuan19
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Asia/Ho_Chi_Minh
          base: ""

          # 📅 Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # 🏆 Achievements
          # plugin_achievements: yes
          # plugin_achievements_threshold: C

          # 🏷️ Most used languages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15

          # 🎵 Music activity and suggestions
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_user: tatuan19
          plugin_music_mode: recent
          plugin_music_limit: 5

          # 🥇 Leetcode (đang tắt, mở lại sau)
          # plugin_leetcode: yes
          # plugin_leetcode_user: tatuan19

          # 🥠 Fortune
          plugin_fortune: yes

      # 🌆 GitHub Skyline
      # - uses: lowlighter/metrics@master
      #   with:
      #     filename: github-skyline.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     user: tatuan19
      #     committer_token: ${{ secrets.GITHUB_TOKEN }}
      #     base: ""
      #     plugin_skyline: yes
      #     plugin_skyline_year: 2026
      #     plugin_skyline_frames: 1
      #     plugin_skyline_quality: 0.3
